### PR TITLE
Adding ffmpeg dependency 

### PR DESCRIPTION
**Pull request by ronan-ln**
and documentation for custom-convert.conf

### CODE REVIEW

**Comment by ronan-ln** [comment]
@DOliana, conflicts resolved, should be ready for your review

**Comment by DOliana** [comment]
@ronan-ln  Could you add some description what the file conversion settings are for (maybe a use case)? I do not know, what files are converted for what reason - is that pulseaudio specific or for lms? (While writing I could imagine that its for lms to have some kind of on the fly conversion - right?)

**Comment by ronan-ln** [comment]
Hi, you're right that this is for on the fly conversion for file types which are not supported natively by the players.
I'll add a bit if description and links to docs if I can find some.

**Comment by DOliana** [comment]
Thanks!

**Pull request merged**
