### PR TITLE
Add LMS v8.0

### PR DESCRIPTION
**Pull request by kidhazy**
Added instructions for building LMS 8.0 image.  Based on code for building LMS 7.9.2 image but provided an updated version.

### CODE REVIEW

**Comment by kidhazy** [comment]
Looking to see if we can expand your work to include builds for LMS v8.0

**Comment by DOliana** [comment]
Thanks! I have added a feature-branch to check the builds - let's see how the build goes.

**Comment by DOliana** [comment]
@kidhazy  The image was built successfully and is available as `doliana/logitech-media-server:latest-AddLMS8.0Image-8.0` I will try it on a raspberry - could you see if it works for you?

**Comment by kidhazy** [comment]
Thanks.

Looks like it's working.  I tested on a RPi 4, and ran local music and
Spotify OK using an iPad as a player.

FYI, I did notice your image was almost 160MB larger than the v8 image I
had built.  But then I remember you now include ffmpeg and pulseaudio in
your build.  Mine didn't.
[image: image.png]

If your testing goes OK I'm sure the community would love to hear your
progress.
https://forums.slimdevices.com/showthread.php?111828-Official-docker-container-for-LMS&p=982072#post982072

Thanks for your efforts.

**Comment by DOliana** [comment]
Cool. I will post in the forum. Are you using the 32 or 64 bit image?

**Comment by kidhazy** [comment]
I'm using ARM7 32bit.

**Pull request merged**
