### PR TITLE
Adding support for Pulseaudio

### PR DESCRIPTION
**Pull request by ronan-ln**
This PR adds support for Pulseaudio. My use case is for the WaveInput plugin to stream directly from Pulseaudio devices.

### CODE REVIEW

**Review by DOliana — APPROVED** [review]
I will temporarily approve the PR to have a build run. This way we can test the image and merge it when ready.

**Comment by DOliana** [comment]
@ronan-ln there are new images with the tag latest-AddPulseAudio-7.9.2 / latest-AddPulseAudio-7.9.0 Could you test the ones relevant for you and let me know the results? If they are OK I can merge them. I will test the armv7 version on raspbian.

**Comment by ronan-ln** [comment]
@DOliana I also use ARM, in my case LibreELEC, and as far as I can tell all is looking good. Thanks for your quick response!

**Comment by DOliana** [comment]
@ronan-ln  looks good for me too - will merge. Did you see the comment in your other PR?

**Pull request merged**
